title: "Shiva Sai Krishna Anand Tokal"
description: "MTech (Research) @ DREAM::LAB | CDS | IISc Bengaluru"
theme: jekyll-theme-cayman

# Navigation Menu
nav:
  - title: "Resume & Research"
    url: /
  - title: "Projects"
    url: /projects
  - title: "Visualizations"
    url: /visualizations

author:
  name: "Shiva Sai Krishna Anand Tokal"
  email: "shivakrishnaanand@gmail.com"
  github: "Shiva-sai-krishna"
  linkedin: "shiva-sai-krishna"
